### ISSUE TITLE
ImportError from graph module

### ISSUE THREAD

**Issue by harryz619** [Jho-Yonsei/HD-GCN#11]
/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/main.py:592: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  default_arg = yaml.load(f)
Traceback (most recent call last):
  File "/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/main.py", line 602, in <module>
    processor = Processor(arg)
  File "/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/main.py", line 251, in __init__
    self.load_model()
  File "/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/main.py", line 293, in load_model
    Model = import_class(self.arg.model)
  File "/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/main.py", line 47, in import_class
    __import__(mod_str)
  File "/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/model/HDGCN.py", line 11, in <module>
    from graph.tools import get_groups
  File "/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/graph/__init__.py", line 3, in <module>
    from . import ntu_rgb_d
ImportError: cannot import name 'ntu_rgb_d' from partially initialized module 'graph' (most likely due to a circular import) (/project/6006955/hzhuang2/hd_gcn_testing/hd_gcn/graph/__init__.py)

I am not sure how to deal with this error when attempting to train the model on nturgb60

**Comment by WeitaoVan** [comment]
Hi, you can solve it by deleting code lines 3 - 4 in file `graph/__init__.py`.
